# To use: cpanm --installdeps .
requires 'Moo';                         # OO Framework
requires 'strictures' => '2';           # Enables strict and warnings with specific settings
requires 'namespace::clean';            # Removes declared and imported symbols from your compiled package
#requires 'Mojo::Discord';               # Discord Library
requires 'FindBin' => '1.51';           # For including libs in the project directory

